name: Test

on:
  push: null
  pull_request: null

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: JoshPiper/Changed-Paths-Action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: "test.yml"
